subnet 10.0.0.0 netmask 255.255.255.0 {
  range 10.0.0.31 10.0.0.250;
  option domain-name-servers 10.0.0.12;
  option domain-name "hye12.local";
  option routers 10.0.0.254;
#  option broadcast-address 10.0.0.254;
  default-lease-time 3600;
  max-lease-time 3600;
}

host w10 {
  hardware ethernet 00:00:00:00:00:01;
  fixed-address 10.0.0.101;
}

host w11 {
  hardware ethernet 00:00:00:00:00:21;
  fixed-address 10.0.0.201;
}
